language: php
php:
  - '5.6'
  - '7.0'
  
services:
  - mongodb
  
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  
script: vendor/bin/phpunit
